server:
  port: 9090

# DataSource settings: set here configurations for the database connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app_apis
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

# File related all configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  image: images/

# Security login customization
#  security:
#    user:
#      name: bikalp
#      password: bikalp
#      roles: ADMIN

